name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: SehawqDB Version
      description: Which version are you using? (e.g. 5.0.0)
      placeholder: 5.0.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: I tried to save a user but it threw an error...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Code to Reproduce
      description: Please provide a minimal code example.
      render: javascript
      placeholder: |
        const db = new SehawqDB();
        db.set('foo', 'bar');
    validations:
      required: true
